server:
  port: 0

spring:
  application:
    name: cliente-ms
  datasource:
    url: jdbc:postgresql://localhost:5432/cliente-ms
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

  instance:
    instance-id: ${spring.application.name}:${random.int}
